name: Boosters
version: '${project.version}'
main: me.github.gavvydizzle.boosters.BoostPlugin
api-version: '1.21'
folia-supported: true
authors: [GavvyDizzle]
description: A command based boost system

depend: [ServerUtils]
softdepend: [CommandDrops, Levels, LuckPerms, PrisonEnchants, ShopGUIPlus]

commands:
  boostadmin:
    aliases: [boostsadmin, boosteradmin, boostersadmin]
    description: BoostPlugin admin commands
    permission: boosters.admin
    permission-message: Insufficient permission
  boost:
    aliases: [boosts, booster, boosters]
    description: BoostPlugin player commands
    permission: boosters.player
    permission-message: Insufficient permission
